# Generated by Django 5.0.6 on 2024-05-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200)),
                ('c_image', models.ImageField(upload_to='shopApp/clothes')),
                ('c_desc', models.TextField()),
                ('c_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('f_image', models.ImageField(upload_to='shopApp/flags')),
                ('f_desc', models.TextField()),
                ('f_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utensils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=200)),
                ('u_image', models.ImageField(upload_to='shopApp/utensils')),
                ('u_desc', models.TextField()),
                ('u_price', models.IntegerField()),
            ],
        ),
    ]
