# Generated by Django 5.0.6 on 2024-06-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='c_original_price',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='flags',
            name='f_original_price',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='utensils',
            name='u_original_price',
            field=models.IntegerField(default=5000),
        ),
    ]
